name: Documentation Generation

on:
  push:
    branches:
      - main  # Déclenche le workflow lorsqu'un commit est poussé dans la branche `main`

jobs:
  generate-documentation:
    runs-on: ubuntu-latest  # Environnement d'exécution sur Ubuntu

    steps:
      # Étape 1 : Checkout du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Configuration de Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      # Étape 3 : Génération de la documentation Javadoc avec Maven
      - name: Generate Javadoc
        run: mvn -B javadoc:javadoc  # Utilisation de la commande Maven pour générer la documentation

      # Étape 4 : Déploiement de la documentation sur GitHub Pages
      - name: Deploy Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Token GitHub pour l'authentification
          publish_dir: ./target/site/apidocs  # Répertoire contenant la documentation générée par Maven
          publish_branch: gh-pages  # Branche où déployer la documentation (gh-pages)
          user_name: 'github-actions'  # Nom de l'utilisateur pour l'engagement
          user_email: 'github-actions@github.com'  # Email de l'utilisateur pour l'engagement

      # (Optionnel) Étape 5 : Téléchargez la documentation générée en tant qu'artefact
      - name: Upload documentation to artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: target/site/apidocs
